# Generated by Django 4.2.3 on 2023-08-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('done', 'done'), ('cancelled', 'cancelled'), ('yet_to_come', 'yet_to_come')], default='yet_to_come', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('time_to_go', models.DurationField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('intro', models.TextField()),
            ],
        ),
    ]
