# Generated by Django 4.2.3 on 2023-08-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UBA_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='intro',
            field=models.TextField(blank=True, default=''),
        ),
    ]
