# Generated by Django 4.2.3 on 2023-08-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UBA_home', '0002_alter_member_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('workshop', 'workshop'), ('general', 'general'), ('speaker_series', 'speaker_series')], default='general', max_length=100),
        ),
    ]
