# Generated by Django 4.2.3 on 2023-08-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UBA_home', '0003_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('WORKSHOP', 'WORKSHOP'), ('GENERAL', 'GENERAL'), ('SPEAKER_SERIES', 'SPEAKER_SERIES')], default='GENERAL', max_length=100),
        ),
    ]
